# Generated by Django 4.2.4 on 2023-08-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_img',
            field=models.CharField(default='https://images.unsplash.com/photo-1589827577276-65d717348780?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bWVra2FofGVufDB8fDB8fHww&auto=format&fit=crop&w=600&q=60', max_length=300),
        ),
    ]
