# Generated by Django 4.2.4 on 2023-08-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likeCount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
